export enum TipoEvento {
    BELLEZA = 'BELLEZA',
    CONCIERTO = 'CONCIERTO',
    CULTURA = 'CULTURA',
    DEPORTE = 'DEPORTE',
    MODA = 'MODA',
    EDUCACION = 'EDUCACION',
    DIVERSION = 'DIVERSION',
}
